# Generated by Django 6.0.1 on 2026-02-01 19:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('ad_soyad', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('not_alani', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benzersiz_kod', models.CharField(blank=True, editable=False, max_length=80, unique=True, verbose_name='Benzersiz kod')),
                ('yer_bilgisi', models.CharField(max_length=500, verbose_name='Yer bilgisi')),
                ('not_alani', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'İstasyon',
                'verbose_name_plural': 'İstasyonlar',
                'ordering': ['zone', 'benzersiz_kod'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, verbose_name='Kod')),
                ('ad', models.CharField(max_length=200, verbose_name='Ad')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('not_alani', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tesisler', to='core.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Tesis',
                'verbose_name_plural': 'Tesisler',
                'ordering': ['customer', 'kod'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('uygulamalar', models.TextField(blank=True, verbose_name='Uygulamalar')),
                ('not_alani', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'İş kaydı',
                'verbose_name_plural': 'İş kayıtları',
                'ordering': ['-tarih', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Talep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Talep tarihi')),
                ('tip', models.CharField(choices=[('sikayet', 'Şikayet'), ('yapilacak', 'Yapılacak')], max_length=20, verbose_name='Tip')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talepler', to='core.customer', verbose_name='Müşteri')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talepler', to='core.facility', verbose_name='Tesis')),
                ('kapatilan_is_kaydi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kapatilan_talepler', to='core.workrecord', verbose_name='Kapatılan iş kaydı')),
            ],
            options={
                'verbose_name': 'Talep',
                'verbose_name_plural': 'Talepler',
                'ordering': ['-tarih', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecordStationCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayim_degeri', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Sayım değeri')),
                ('not_alani', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sayim_kayitlari', to='core.station', verbose_name='İstasyon')),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_counts', to='core.workrecord', verbose_name='İş kaydı')),
            ],
            options={
                'verbose_name': 'İş kaydı istasyon sayımı',
                'verbose_name_plural': 'İş kaydı istasyon sayımları',
                'ordering': ['work_record', 'station'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20, verbose_name='Kod')),
                ('ad', models.CharField(max_length=200, verbose_name='Ad')),
                ('not_alani', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolgeler', to='core.facility', verbose_name='Tesis')),
            ],
            options={
                'verbose_name': 'Bölge',
                'verbose_name_plural': 'Bölgeler',
                'ordering': ['facility', 'kod'],
            },
        ),
        migrations.AddField(
            model_name='station',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='istasyonlar', to='core.zone', verbose_name='Bölge'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('customer', 'kod'), name='unique_customer_facility_kod'),
        ),
        migrations.AddConstraint(
            model_name='workrecordstationcount',
            constraint=models.UniqueConstraint(fields=('work_record', 'station'), name='unique_workrecord_station'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('facility', 'kod'), name='unique_facility_zone_kod'),
        ),
    ]
