# Generated by Django 6.0.1 on 2026-02-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_firma_yetkili'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='yetkili_ad_soyad',
        ),
    ]
