# Generated by Django 6.0.1 on 2026-02-08 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customer_email_remove_customer_telefon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, help_text='Kare formatta yükleyin. Yüklemeden önce hizalayıp kırpabilirsiniz.', null=True, upload_to='customer_logos/%Y/%m/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='ad',
            field=models.CharField(max_length=200, verbose_name='Tesis adı'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Kare formatta yükleyin. Yüklemeden önce hizalayıp kırpabilirsiniz.', null=True, upload_to='avatars/%Y/%m/', verbose_name='Profil fotoğrafı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı profili',
                'verbose_name_plural': 'Kullanıcı profilleri',
            },
        ),
    ]
