# Generated by Django 6.0.1 on 2026-02-08

from django.db import migrations, models


def migrate_yer_bilgisi_to_ad(apps, schema_editor):
    Station = apps.get_model("core", "Station")
    for s in Station.objects.all():
        s.ad = (s.yer_bilgisi or "")[:150]
        s.save(update_fields=["ad"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofile_and_customer_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="ad",
            field=models.CharField(default="", max_length=150, verbose_name="Ad"),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_yer_bilgisi_to_ad, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="station",
            name="yer_bilgisi",
        ),
        migrations.RemoveField(
            model_name="station",
            name="not_alani",
        ),
    ]
