# Generated by Django 6.0.1 on 2026-02-08

from django.db import migrations, models


def fill_kod_from_benzersiz(apps, schema_editor):
    Station = apps.get_model("core", "Station")
    for s in Station.objects.all():
        if s.benzersiz_kod and "-" in s.benzersiz_kod:
            s.kod = s.benzersiz_kod.rsplit("-", 1)[-1][:20]
        else:
            s.kod = str(s.pk) if s.pk else "1"
        s.save(update_fields=["kod"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_station_ad_replace_yer_bilgisi_not"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="kod",
            field=models.CharField(default="", max_length=20, verbose_name="Kod"),
            preserve_default=False,
        ),
        migrations.RunPython(fill_kod_from_benzersiz, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("zone", "kod"),
                name="unique_zone_station_kod",
            ),
        ),
    ]
