# Generated by Django 6.0.1 on 2026-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ekip_talep_planlanan_onetoone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['zone', 'kod'], 'verbose_name': 'İstasyon', 'verbose_name_plural': 'İstasyonlar'},
        ),
        migrations.AddField(
            model_name='talep',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Beklemede'), ('planlandi', 'Planlandı'), ('yapildi', 'Yapıldı')], default='beklemede', max_length=20, verbose_name='Durum'),
        ),
    ]
