# Generated by Django 6.0.1 on 2026-02-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_talep_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='talep',
            name='iliski_talep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bagli_talepler', to='core.talep', verbose_name='İlişkili talep'),
        ),
    ]
