# Generated by Django 6.0.1 on 2026-02-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_talep_iliski_talep_ve_durum_otomatik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periyod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, help_text='Tanım adı (isteğe bağlı)', max_length=200, verbose_name='Ad')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç tarihi')),
                ('bitis_tarihi', models.DateField(blank=True, help_text='Boşsa süresiz tekrarlanır.', null=True, verbose_name='Bitiş tarihi')),
                ('tekrar_sayisi', models.PositiveSmallIntegerField(blank=True, help_text='Bu kadar oluşturduktan sonra dur. Boşsa bitiş tarihine kadar.', null=True, verbose_name='Tekrar sayısı')),
                ('siklik', models.CharField(choices=[('gunluk', 'Günlük'), ('haftalik', 'Haftalık'), ('aylik', 'Aylık'), ('yillik', 'Yıllık')], default='haftalik', max_length=20, verbose_name='Sıklık')),
                ('aralik', models.PositiveSmallIntegerField(default=1, help_text='Her kaç birimde bir (örn. her 2 hafta için 2).', verbose_name='Aralık')),
                ('haftanin_gunleri', models.CharField(blank=True, help_text='Haftalık için: 1=Pzt, 2=Sal, 3=Çar, 4=Per, 5=Cum, 6=Cmt, 7=Paz. Virgülle ayırın (örn. 1,3,5).', max_length=50, verbose_name='Haftanın günleri')),
                ('ayin_gunu', models.PositiveSmallIntegerField(blank=True, help_text='Aylık için: 1-31 arası.', null=True, verbose_name='Ayın günü')),
                ('ay', models.PositiveSmallIntegerField(blank=True, help_text='Yıllık için: 1-12 arası.', null=True, verbose_name='Ay')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periyodlar', to='core.customer', verbose_name='Müşteri')),
                ('facility', models.ForeignKey(blank=True, help_text='Boş bırakılırsa müşteri geneli kabul edilebilir.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periyodlar', to='core.facility', verbose_name='Tesis')),
            ],
            options={
                'verbose_name': 'Periyod',
                'verbose_name_plural': 'Periyodlar',
                'ordering': ['customer', 'facility', 'baslangic_tarihi'],
            },
        ),
    ]
