# Generated by Django 6.0.1 on 2026-02-08 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_periyod_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='periyod',
            name='talep_tipi',
            field=models.ForeignKey(blank=True, help_text='Otomatik oluşturulacak taleplerin tipi. Boş bırakılabilir.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periyodlar', to='core.taleptipi', verbose_name='Talep tipi'),
        ),
    ]
