# Generated by Django 6.0.1 on 2026-02-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_periyod_talep_tipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='baslama_saati',
            field=models.TimeField(blank=True, null=True, verbose_name='Başlama saati'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='bitis_saati',
            field=models.TimeField(blank=True, null=True, verbose_name='Bitiş saati'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='ekip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_kayitlari', to='core.ekip', verbose_name='Ekip'),
        ),
    ]
