# Generated by Django 6.0.1 on 2026-02-08 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_workrecord_ekip_ve_saatler'),
    ]

    operations = [
        migrations.CreateModel(
            name='UygulamaTanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=300, verbose_name='Uygulama')),
                ('sira', models.PositiveSmallIntegerField(default=0, help_text='Liste sıralaması', verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Uygulama tanımı',
                'verbose_name_plural': 'Uygulama tanımları',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.RenameField(
            model_name='workrecord',
            old_name='uygulamalar',
            new_name='oneriler',
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='oneriler',
            field=models.TextField(blank=True, verbose_name='Öneriler'),
        ),
        migrations.CreateModel(
            name='WorkRecordUygulama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uygulama_tanim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_kaydi_satirlari', to='core.uygulamatanim', verbose_name='Uygulama')),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yapilan_uygulamalar', to='core.workrecord', verbose_name='İş kaydı')),
            ],
            options={
                'verbose_name': 'Yapılan uygulama',
                'verbose_name_plural': 'Yapılan uygulamalar',
                'constraints': [models.UniqueConstraint(fields=('work_record', 'uygulama_tanim'), name='unique_workrecord_uygulama')],
            },
        ),
    ]
