# Generated by Django 6.0.1 on 2026-02-08 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_uygulama_tanimlari_ve_yapilan_uygulamalar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TespitTanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=300, verbose_name='Tespit')),
                ('sira', models.PositiveSmallIntegerField(default=0, help_text='Liste sıralaması', verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Tespit tanımı',
                'verbose_name_plural': 'Tespit tanımları',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecordTespit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yogunluk', models.CharField(choices=[('az', 'Az'), ('cok', 'Çok'), ('istila', 'İstila')], default='az', max_length=20, verbose_name='Yoğunluk')),
                ('tespit_eden', models.CharField(choices=[('musteri', 'Müşteri'), ('firma', 'Firma')], default='firma', max_length=20, verbose_name='Tespit eden')),
                ('tespit_tanim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_kaydi_tespitleri', to='core.tespittanim', verbose_name='Tespit')),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tespitler', to='core.workrecord', verbose_name='İş kaydı')),
            ],
            options={
                'verbose_name': 'Tespit',
                'verbose_name_plural': 'Tespitler',
                'ordering': ['work_record', 'tespit_tanim'],
            },
        ),
    ]
