# Generated by Django 6.0.1 on 2026-02-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_workrecord_flags_ve_talep_iliskisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='form_numarasi',
            field=models.CharField(blank=True, editable=False, help_text='Otomatik: Müşteri kodu-Tesis kodu-YYYYMMDD (kapatılan talep varsa).', max_length=80, verbose_name='Form numarası'),
        ),
    ]
