# Generated by Django 6.0.1 on 2026-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_workrecord_form_numarasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecordstationcount',
            name='not_alani',
            field=models.CharField(blank=True, max_length=200, verbose_name='Not'),
        ),
    ]
