# Generated by Django 6.0.1 on 2026-02-08 15:11

from django.db import migrations, models


def sayim_degeri_to_int(apps, schema_editor):
    WorkRecordStationCount = apps.get_model('core', 'WorkRecordStationCount')
    for obj in WorkRecordStationCount.objects.all():
        try:
            obj.sayim_degeri = max(0, int(round(float(obj.sayim_degeri))))
            obj.save(update_fields=['sayim_degeri'])
        except (TypeError, ValueError):
            obj.sayim_degeri = 0
            obj.save(update_fields=['sayim_degeri'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_workrecordstationcount_not_alani_char200'),
    ]

    operations = [
        migrations.RunPython(sayim_degeri_to_int, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workrecordstationcount',
            name='sayim_degeri',
            field=models.PositiveIntegerField(default=0, verbose_name='Sayım değeri'),
        ),
    ]
