# Generated by Django 6.0.1 on 2026-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_workrecordstationcount_sayim_degeri_positiveinteger'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='ar_uz_ulv',
            field=models.BooleanField(default=False, verbose_name='Ar.Üz. ULV'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='atomizor',
            field=models.BooleanField(default=False, verbose_name='Atomizör'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='civi_tabancasi',
            field=models.BooleanField(default=False, verbose_name='Çivi Tabancası'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='elk_ulv',
            field=models.BooleanField(default=False, verbose_name='Elk. ULV'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='pulverizator',
            field=models.BooleanField(default=False, verbose_name='Pülverizatör'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='skb',
            field=models.BooleanField(default=False, verbose_name='SKB'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='termal_sis',
            field=models.BooleanField(default=False, verbose_name='Termal Sis.'),
        ),
    ]
