# Generated by Django 6.0.1 on 2026-02-08 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_workrecord_makine_ekipman_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaaliyetTanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=300, verbose_name='Faaliyet')),
                ('sira', models.PositiveSmallIntegerField(default=0, help_text='Liste sıralaması', verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Faaliyet tanımı',
                'verbose_name_plural': 'Faaliyet tanımları',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecordFaaliyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontrol', models.BooleanField(default=False, verbose_name='Kontrol')),
                ('kuruldu', models.BooleanField(default=False, verbose_name='Kuruldu')),
                ('eklendi', models.BooleanField(default=False, verbose_name='Eklendi')),
                ('sabitlendi', models.BooleanField(default=False, verbose_name='Sabitlendi')),
                ('yeri_degistirildi', models.BooleanField(default=False, verbose_name='Yeri Değiştirildi')),
                ('yenilendi', models.BooleanField(default=False, verbose_name='Yenilendi')),
                ('faaliyet_tanim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_kaydi_satirlari', to='core.faaliyettanim', verbose_name='Faaliyet')),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faaliyetler', to='core.workrecord', verbose_name='İş kaydı')),
            ],
            options={
                'verbose_name': 'İş kaydı faaliyet',
                'verbose_name_plural': 'İş kaydı faaliyetler',
                'ordering': ['work_record', 'faaliyet_tanim'],
                'constraints': [models.UniqueConstraint(fields=('work_record', 'faaliyet_tanim'), name='unique_workrecord_faaliyet')],
            },
        ),
    ]
