# Generated by Django 6.0.1 on 2026-02-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_faaliyet_tanim_workrecord_faaliyet'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlacTanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temin_edildigi_firma', models.CharField(blank=True, max_length=150, verbose_name='Temin Edildiği Firma')),
                ('ticari_ismi', models.CharField(max_length=150, verbose_name='Ticari İsmi')),
                ('aktif_madde', models.CharField(blank=True, max_length=100, verbose_name='Aktif Madde')),
                ('ambalaj', models.CharField(blank=True, max_length=20, verbose_name='Ambalaj')),
                ('antidot', models.CharField(blank=True, max_length=50, verbose_name='Antidot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'İlaç tanımı',
                'verbose_name_plural': 'İlaç tanımları',
                'ordering': ['ticari_ismi'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecordIlac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Miktar')),
                ('ilac_tanim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_kaydi_satirlari', to='core.ilactanim', verbose_name='İlaç')),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanilan_ilaclar', to='core.workrecord', verbose_name='İş kaydı')),
            ],
            options={
                'verbose_name': 'Kullanılan ilaç',
                'verbose_name_plural': 'Kullanılan ilaçlar',
                'ordering': ['work_record', 'ilac_tanim'],
                'constraints': [models.UniqueConstraint(fields=('work_record', 'ilac_tanim'), name='unique_workrecord_ilac')],
            },
        ),
    ]
