# Generated by Django 6.0.1 on 2026-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ilac_tanim_workrecord_ilac'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilactanim',
            name='aktif',
            field=models.BooleanField(default=True, help_text='Pasif ilaçlar yeni iş kaydında seçilemez; mevcut kayıtlar görünür kalır.', verbose_name='Aktif'),
        ),
    ]
