# Generated by Django 6.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ilactanim_aktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaaliyetRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_kod', models.CharField(max_length=20, verbose_name='Müşteri kodu')),
                ('is_kaydi_kod', models.CharField(max_length=80, verbose_name='İş kaydı kodu (form no)')),
                ('rapor_tarihi', models.DateField(verbose_name='Rapor tarihi')),
                ('rapor_olusturuldu', models.BooleanField(default=False, verbose_name='Rapor oluşturuldu')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='faaliyet_raporlari/%Y/%m/', verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('work_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faaliyet_raporu', to='core.workrecord', verbose_name='İş kaydı')),
            ],
            options={
                'verbose_name': 'Faaliyet raporu',
                'verbose_name_plural': 'Faaliyet raporları',
                'ordering': ['-rapor_tarihi', '-created_at'],
            },
        ),
    ]
