# Generated by Django 6.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_faaliyetraporu'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(
                blank=True,
                help_text='Bu kullanıcının bağlı olduğu müşteri (opsiyonel).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='user_profiles',
                to='core.customer',
                verbose_name='Geçerli müşteri',
            ),
        ),
    ]
