# Generated by Django 6.0.1 on 2026-02-12

from django.db import migrations, models


def sayim_to_tuketim(apps, schema_editor):
    """sayim_degeri > 0 -> tuketim_var=True, aksi halde False."""
    WorkRecordStationCount = apps.get_model("core", "WorkRecordStationCount")
    for obj in WorkRecordStationCount.objects.all():
        obj.tuketim_var = (obj.sayim_degeri or 0) > 0
        obj.save(update_fields=["tuketim_var"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_userprofile_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrecordstationcount",
            name="tuketim_var",
            field=models.BooleanField(default=False, help_text="True: tüketim var, False: tüketim yok.", verbose_name="Tüketim var"),
        ),
        migrations.RunPython(sayim_to_tuketim, reverse_noop),
        migrations.RemoveField(
            model_name="workrecordstationcount",
            name="sayim_degeri",
        ),
    ]
