# Generated by Django 6.0.1 on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_workrecordstationcount_tuketim_var"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrecord",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="is_kayitlari",
                to="core.customer",
                verbose_name="Müşteri",
            ),
        ),
        migrations.AddField(
            model_name="workrecord",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="is_kayitlari",
                to="core.facility",
                verbose_name="Tesis",
            ),
        ),
    ]
