# Generated by Django 6.0.1 on 2026-02-12

from django.db import migrations, models


def set_initial_durum(apps, schema_editor):
    """Mevcut kayıtlar: bitis_saati doluysa Tamamlandı, baslama_saati doluysa Devam Ediyor, yoksa Başlanmadı."""
    WorkRecord = apps.get_model("core", "WorkRecord")
    for wr in WorkRecord.objects.all():
        if wr.bitis_saati:
            wr.durum = "tamamlandi"
        elif wr.baslama_saati:
            wr.durum = "devam_ediyor"
        else:
            wr.durum = "baslanmadi"
        wr.save(update_fields=["durum"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_workrecord_customer_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrecord",
            name="durum",
            field=models.CharField(
                choices=[
                    ("baslanmadi", "Başlanmadı"),
                    ("devam_ediyor", "Devam Ediyor"),
                    ("tamamlandi", "Tamamlandı"),
                ],
                default="baslanmadi",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.RunPython(set_initial_durum, migrations.RunPython.noop),
    ]
