# Generated by Django 6.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_workrecord_durum"),
    ]

    operations = [
        migrations.CreateModel(
            name="BagimsizTespit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tarih", models.DateField(verbose_name="Tarih")),
                ("yer_aciklamasi", models.TextField(blank=True, verbose_name="Yer açıklaması")),
                ("gozlem_aciklamasi", models.TextField(blank=True, verbose_name="Gözlem açıklaması")),
                ("oneriler", models.TextField(blank=True, verbose_name="Öneriler")),
                ("raporlandi", models.BooleanField(default=False, verbose_name="Raporlandı")),
                ("gorsel1", models.ImageField(blank=True, null=True, upload_to="bagimsiz_tespit/%Y/%m/", verbose_name="Görsel 1")),
                ("gorsel2", models.ImageField(blank=True, null=True, upload_to="bagimsiz_tespit/%Y/%m/", verbose_name="Görsel 2")),
                ("gorsel3", models.ImageField(blank=True, null=True, upload_to="bagimsiz_tespit/%Y/%m/", verbose_name="Görsel 3")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma")),
                ("firma", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bagimsiz_tespitler", to="core.customer", verbose_name="Firma")),
                ("tesis", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="bagimsiz_tespitler", to="core.facility", verbose_name="Tesis")),
            ],
            options={
                "verbose_name": "Bağımsız tespit",
                "verbose_name_plural": "Bağımsız tespitler",
                "ordering": ["-tarih", "-created_at"],
            },
        ),
    ]
