# Generated by Django 5.2.4 on 2026-02-19 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_bagimsiz_tespit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Belirli bir tesisle sınırlamak için (opsiyonel). Boşsa müşterinin tüm tesislerini görebilir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.facility', verbose_name='Tesis'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_client',
            field=models.BooleanField(blank=True, default=False, help_text='Bu kullanıcı müşteri portalına erişebilir.', verbose_name='Müşteri tarafı kullanıcı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Bu kullanıcının bağlı olduğu müşteri (opsiyonel). Tesis boşsa müşterinin tüm tesislerini görebilir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.customer', verbose_name='Müşteri'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='form_numarasi',
            field=models.CharField(blank=True, editable=False, help_text='Otomatik: Müşteri kodu-Tesis kodu-YYYYMMDD (iş kaydı veya kapatılan talep üzerinden).', max_length=80, verbose_name='Form numarası'),
        ),
    ]
