# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_userprofile_is_client_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="bagimsiztespit",
            name="durum",
            field=models.CharField(
                choices=[("tespit_edildi", "Tespit edildi"), ("cozuldu", "Çözüldü")],
                default="tespit_edildi",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AddField(
            model_name="bagimsiztespit",
            name="cozumlenme_tarihi",
            field=models.DateField(blank=True, null=True, verbose_name="Çözümlenme tarihi"),
        ),
    ]
