# Generated by Django 6.0.1 on 2026-02-01 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_customer_email_remove_customer_telefon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Kategori adı')),
                ('sira', models.PositiveSmallIntegerField(default=0, help_text='Liste sıralaması', verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'İletişim kategorisi',
                'verbose_name_plural': 'İletişim kategorileri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=200, verbose_name='Adı soyadı')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('not_alani', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.customer', verbose_name='Müşteri')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.facility', verbose_name='Tesis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='addressbook.contactcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişimler',
                'ordering': ['category', 'ad_soyad'],
            },
        ),
    ]
