# Generated by Django 6.0.1 on 2026-02-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_default_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='adres',
        ),
        migrations.AlterField(
            model_name='contact',
            name='not_alani',
            field=models.CharField(blank=True, max_length=200, verbose_name='Not'),
        ),
    ]
