"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ortam değişkenleri (.env dosyasından)
env = environ.Env(
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, []),
)

# .env dosyası proje kökünde (manage.py ile aynı)
env_file = BASE_DIR / ".env"
if env_file.exists():
    env.read_env(str(env_file))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", default="django-insecure-9he57i4o*=_jhvcr^l(l$*@%5)g!g$52uds36=n6^55&&@6+8=")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

_allowed = [h.strip() for h in env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"]) if h and h.strip()]
ALLOWED_HOSTS = _allowed if _allowed else ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'addressbook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_default_db = f"sqlite:///{BASE_DIR / 'db.sqlite3'}".replace("\\", "/")
DATABASES = {
    "default": env.db("DATABASE_URL", default=_default_db)
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization — tamamen Türkçe arayüz
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "tr"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True

# Türkiye: Haftanın ilk günü Pazartesi
FIRST_DAY_OF_WEEK = 1


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "statics"]
STATIC_ROOT = env.path("STATIC_ROOT", default=BASE_DIR / "staticfiles")

# Yüklenen dosyalar (avatar, müşteri logosu)
MEDIA_URL = "media/"
MEDIA_ROOT = env.path("MEDIA_ROOT", default=BASE_DIR / "media")

# Auth (frontend login; kullanıcılar admin'den tanımlanır)
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Unfold admin: sol menü grupları, sol üst başlık, logo, dashboard
UNFOLD = {
    "SITE_HEADER": "Kale İlaçlama",
    "SITE_LOGO": "/static/logo.png",
    "SIDEBAR": {
        "show_search": False,
        "show_all_applications": False,
        "navigation": "config.unfold_nav.get_sidebar_navigation",
    },
    "DASHBOARD_CALLBACK": "config.dashboard.admin_dashboard_callback",
}
